DROP TABLE CLIENTE;
DROP TABLE RESERVA;
DROP TABLE GARAJE;
DROP TABLE VEHICULO;

--CREACION DE TABLAS 

CREATE TABLE CLIENTE (
    CL_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    CL_PRIMER_NOMBRE VARCHAR2(40) NOT NULL,
    CL_SEGUNDO_NOMBRE VARCHAR2(40) NOT NULL,
    CL_PRIMER_APELLIDO VARCHAR2(40) NOT NULL,
    CL_SEGUNDO_APELLIDO VARCHAR2(40) NOT NULL,
    --CL_TELEFONOS
    CL_DIRECCION VARCHAR(255) NOT NULL,
    
    --PRIMARY KEY
    CONSTRAINT PK_CL_ID PRIMARY KEY(CL_ID),
    
    --CONSTRAINTS
    CONSTRAINT CK_CL_PRIMER_NOMBRE CHECK(LENGTH(CL_PRIMER_NOMBRE) >= 2),
    CONSTRAINT CK_CL_SEGUNDO_NOMBRE CHECK(LENGTH(CL_SEGUNDO_NOMBRE) >= 2),
    CONSTRAINT CK_CL_PRIMER_APELLIDO CHECK(LENGTH(CL_PRIMER_APELLIDO) >= 2),
    CONSTRAINT CK_CL_SEGUNDO_APELLIDO CHECK(LENGTH(CL_SEGUNDO_APELLIDO) >= 2),
    --CONSTRAINT TELEFONOS
    CONSTRAINT CK_CL_DIRECCION CHECK(LENGTH(CL_DIRECCION) >= 10)
);

CREATE TABLE RESERVA(
    RS_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    RS_PRECIO DECIMAL(5,2) NOT NULL,
    --REVISAR FECHAS
    RS_FECHA_INICIO DATE NOT NULL,
    RS_FECHA_FINAL DATE NOT NULL,
    RS_DIAS_RESERVA INTEGER NOT NULL,
    
    --PRIMARY KEY
    CONSTRAINT PK_RS_ID PRIMARY KEY(RS_ID)
    
    --CONSTRAINTS
);


CREATE TABLE GARAJE(
    GJ_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    
    --PRIMARY KEY
    CONSTRAINT PK_GJ_ID PRIMARY KEY(GJ_ID)
);

CREATE TABLE VEHICULO(
    VH_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    VH_MARCA VARCHAR2(15) NOT NULL,
    VH_MODELO VARCHAR2(15) NOT NULL,
    VH_PLACA INTEGER NOT NULL,
    VH_COLOR VARCHAR2(10) NOT NULL,
    VH_LITROS_GASOLINA DECIMAL(5,2) NOT NULL,
    VH_PRECIO_X_HORA DECIMAL(5,2) NOT NULL,
    
    --PRIMARY KEY
    CONSTRAINT PK_VH_ID PRIMARY KEY(VH_ID)
    
    --CONSTRAINTS
);


--CREACION TABLAS DE CLAVES FORANEAS