DROP TABLE CLIENTE;
DROP TABLE RESERVA;
DROP TABLE RESERVA_X_CLIENTE;
DROP TABLE TELEFONOS_X_CLIENTE;

DROP TABLE GARAJE;
DROP TABLE VEHICULO;

--CREACION DE TABLAS 

CREATE TABLE CLIENTE (
    CL_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    CL_PRIMER_NOMBRE VARCHAR2(40) NOT NULL,
    CL_SEGUNDO_NOMBRE VARCHAR2(40) NOT NULL,
    CL_PRIMER_APELLIDO VARCHAR2(40) NOT NULL,
    CL_SEGUNDO_APELLIDO VARCHAR2(40) NOT NULL,
    --CL_TELEFONOS
    CL_DIRECCION VARCHAR(255) NOT NULL,
    
    --PRIMARY KEY
    CONSTRAINT PK_CL_ID PRIMARY KEY(CL_ID)
);

--ATRIBUTO MULTIVALUADO TELEFONOS
CREATE TABLE TELEFONOS_X_CLIENTE (
    TXC_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    TXC_CL_ID INTEGER NOT NULL,
    TXC_NUMERO INTEGER NOT NULL,
    
    CONSTRAINT PK_TXC_ID PRIMARY KEY(TXC_ID),
    CONSTRAINT FK_TXC_CL FOREIGN KEY(TXC_CL_ID) REFERENCES CLIENTE(CL_ID)
    --CONSTRIANTS
);

CREATE TABLE RESERVA(
    RS_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    RS_PRECIO DECIMAL(5,2) NOT NULL,
    --REVISAR FECHAS
    RS_FECHA_INICIO DATE NOT NULL,
    RS_FECHA_FINAL DATE NOT NULL,
    RS_DIAS_RESERVA INTEGER NOT NULL,
    
    --PRIMARY KEY
    CONSTRAINT PK_RS_ID PRIMARY KEY(RS_ID)
);

CREATE TABLE RESERVA_X_CLIENTE(
    RXC_CL_ID INTEGER NOT NULL,
    RXC_RS_ID INTEGER NOT NULL,
    
    --LLAVE PRIMARY COMPUESTA
    CONSTRAINT PK_RXC_CL_RS PRIMARY KEY (RXC_CL_ID, RXC_RS_ID),
    CONSTRAINT FK_RXC_CL FOREIGN KEY(RXC_CL_ID) REFERENCES CLIENTE(CL_ID),
    CONSTRAINT FK_RXC_RS FOREIGN KEY(RXC_RS_ID) REFERENCES RESERVA(RS_ID)
    
    --CONSTRIANTS
);



--------------------------------------------------------


CREATE TABLE GARAJE(
    GJ_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    
    --PRIMARY KEY
    CONSTRAINT PK_GJ_ID PRIMARY KEY(GJ_ID)
);

CREATE TABLE VEHICULO(
    VH_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    VH_MARCA VARCHAR2(15) NOT NULL,
    VH_MODELO VARCHAR2(15) NOT NULL,
    VH_PLACA INTEGER NOT NULL,
    VH_COLOR VARCHAR2(10) NOT NULL,
    VH_LITROS_GASOLINA DECIMAL(5,2) NOT NULL,
    VH_PRECIO_X_HORA DECIMAL(5,2) NOT NULL,
    
    --PRIMARY KEY
    CONSTRAINT PK_VH_ID PRIMARY KEY(VH_ID)
    
    --CONSTRAINTS
);

CREATE TABLE GARAJE_X_VEHICULO(
    GXV_GJ_ID INTEGER NOT NULL,
    GXV_VH_ID INTEGER NOT NULL,
    
    --LLAVE PRIMARY COMPUESTA
    CONSTRAINT PK_GXV_GJ_VH PRIMARY KEY (GXV_GJ_ID, GXV_VH_ID),
    CONSTRAINT FK_GXV_GJ FOREIGN KEY(GXV_GJ_ID) REFERENCES GARAJE(GJ_ID),
    CONSTRAINT FK_GXV_VH FOREIGN KEY(GXV_VH_ID) REFERENCES VEHICULO(VH_ID)
    
    --CONSTRIANTS
);



